### ISSUE TITLE
Using NMF metamodels in Unity

### ISSUE THREAD

**Issue by RobertWalterU3d** [NMFCode/NMF#59]
Hi, I 'm new to this project so I might be doing something fundamentally wrong.

I followed this video tutorial: https://www.youtube.com/watch?v=NIMYuwTltVs&feature=youtu.be (First steps with NMF)

I was able to generate my C# types from my ecore file as well as the *.nmf file.
My issue stems from the fact that I try to now use these generated files in the context of a Unity package, which usually doesn't have an AssemblyInfo.cs file to register the ModelMetadata. I'm a bit lost (since I'm also new to Unity) to understand how I can register the ModelMetadata in a Unity package. Any help would be appreciated.

**Comment by georghinkel** [comment]
Hi,

the AssemblyInfo.cs is only recommended because it fits into the common conventions as a place that stores assembly-wide attributes/annotations. However, since Microsoft decided to migrate the information that used to be contained in the AssemblyInfo.cs to the project file for SDK-based project files, many projects do not have an AssemblyInfo.cs anymore.

The short solution is, simply put the code somewhere else. I would recommend to create a file called ModelRegistrations.cs or similar such that peer developers have a place where they can look whether there are models registered. However, the exact location totally doesn't matter, the distribution of code to C# files entirely disappears during build (and is afterwards only contained in PDBs that you don't distribute).

Best,

Georg

**Comment by RobertWalterU3d** [comment]
Thanks, can you point me to the code that allows me to register the model?

**Comment by georghinkel** [comment]
It is really just the annotation that you have to add like here:

https://github.com/NMFCode/NMF/blob/b0362ec5683867748d3e961ebc70e0c5cdb4012e/Models/Models.Tests/Properties/AssemblyInfo.cs#L39

**Comment by RobertWalterU3d** [comment]
okay, now I get this exception when trying to call the ctor ModelRepository:
`Exception: The assembly Unity.StoryGraph, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null declares a model but has no embedded resources. Did you forget to embed a model?`

I guess it is caused by my sgl.nmf is not recognized as an embedded resource, not sure how to achieve that...
